### ISSUE TITLE
Can't disable datafixer?

### ISSUE THREAD

**Issue by Abalieno** [Layers-of-Railways/Railway#186]
That issue should have been addressed, but I set datafixers to be off anyway, but it's crashing on start.

I don't think it should do this.

```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'railways'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
```
```
Caused by: java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:143)
	at com.mojang.datafixers.schemas.Schema.buildTypes(Schema.java:50)
	at com.mojang.datafixers.schemas.Schema.<init>(Schema.java:38)
	at net.minecraft.class_1220.<init>(class_1220.java:14)
	at com.mojang.datafixers.DataFixerBuilder.addSchema(DataFixerBuilder.java:43)
	at com.mojang.datafixers.DataFixerBuilder.addSchema(DataFixerBuilder.java:37)
	at com.railwayteam.railways.registry.CRDataFixers.addFixers(CRDataFixers.java:34)
	at com.railwayteam.railways.registry.CRDataFixers.register(CRDataFixers.java:24)
	at com.railwayteam.railways.ModSetup.register(ModSetup.java:20)
	at com.railwayteam.railways.Railways.init(Railways.java:58)
	at com.railwayteam.railways.fabric.RailwaysImpl.onInitialize(RailwaysImpl.java:22)
```

Turning datafixers back on does work, but I guess being an option it should be possible to keep them off by default.

**Comment by IThundxr** [comment]
Data fixers shouldn't be turned off since otherwise stuff between updates could break

**Comment by techno-sam** [comment]
For @IThundxr:
Right now, the only datafixer that we have is to upgrade monobogeys from pre-0.5.1 worlds, and the config option is added as an escape hatch for server owners who notice our datafixer causing serious lag (bug should have been fixed, but just in case.)

If in any future version datafixer is extended, then the config option will be removed or limited
