### ISSUE TITLE
train path finding issue

### ISSUE THREAD

**Issue by techno-sam** [Layers-of-Railways/Railway#511]
> [!Note]
> Mirror of Creators-of-Create/Create#6810

### Description
when i place new turn, train just turned on it instead coming straight to the station
![image](https://github.com/user-attachments/assets/013f3521-52f4-4204-8f44-91fb4854b165)

### Game Log
[07:23:57] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2885@1176381b, suppressing error java.lang.IllegalArgumentException: Cannot set property class_2746{name=turn, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{railways:generic_crossing} at net.minecraft.class_2688.method_11657(class_2688.java:122) ~[server-intermediary.jar:?] at com.simibubi.create.content.trains.track.TrackPlacement.placeTracks(TrackPlacement.java:535) ~[create-fabric-0.5.1-f-build.1417+mc1.20.1.jar:?] at com.simibubi.create.content.trains.track.TrackPlacement.tryConnect(TrackPlacement.java:456) ~[create-fabric-0.5.1-f-build.1417+mc1.20.1.jar:?] at com.simibubi.create.content.trains.track.TrackBlockItem.method_7884(TrackBlockItem.java:104) ~[create-fabric-0.5.1-f-build.1417+mc1.20.1.jar:?] at net.minecraft.class_1799.method_7981(class_1799.java:272) ~[server-intermediary.jar:?] at net.minecraft.class_3225.method_14262(class_3225.java:363) ~[server-intermediary.jar:?] at net.minecraft.class_3244.method_12046(class_3244.java:1140) ~[server-intermediary.jar:?] at net.minecraft.class_2885.method_12547(class_2885.java:34) ~[server-intermediary.jar:?] at net.minecraft.class_2885.method_11054(class_2885.java:8) ~[server-intermediary.jar:?] at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[server-intermediary.jar:?] at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?] at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?] at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?] at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782) ~[server-intermediary.jar:?] at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[server-intermediary.jar:?] at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?] at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:12318) ~[server-intermediary.jar:?] at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[server-intermediary.jar:?] at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[server-intermediary.jar:?] at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:742) ~[server-intermediary.jar:?] at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[server-intermediary.jar:?] at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?] at java.lang.Thread.run(Thread.java:1583) ~[?:?]

### Debug Information
i just place new turn on my railway

**Comment by techno-sam** [comment]
Note to self: generic crossings may not be converting back into regular tracks when they stop being a crossing

**Comment by techno-sam** [comment]
cc: @IshuCute
